permissionset 50000 "OTL GeneratedPermission"
{
    Assignable = true;
    Permissions = tabledata Car = RIMD,
        tabledata "Car Manufacturer" = RIMD,
        tabledata "Car Model" = RIMD,
        table Car = X,
        table "Car Manufacturer" = X,
        table "Car Model" = X,
        report CarReport = X,
        codeunit CarUpgrade = X,
        codeunit "Car Factory" = X,
        codeunit "Car Factory Impl." = X,
        codeunit ExportXMLPort = X,
        xmlport CarExport = X,
        page "Car Act." = X,
        page "Car Card" = X,
        page "Car List" = X,
        page "Car Manufacturer" = X,
        page "Car Model" = X,
        page "Car Role Center" = X,
        page MyPage = X,
        tabledata "Car Setup" = RIMD,
        table "Car Setup" = X,
        codeunit "Car Assisted Setup Subs" = X,
        codeunit "Create Sales Order" = X,
        codeunit MyEDocuments = X,
        codeunit MyListCodeunit = X,
        codeunit MyTestCodeunit = X,
        codeunit TryCodeunit = X,
        page "Car Setup" = X,
        page CarAssistedSetup = X,
        page ControlAddinPage = X,
        query MyQuery = X;
}